/*
 * $ Copyright 2016-YEAR Cypress Semiconductor $
 */
#pragma once

#include <wiced_result.h>
#include <hal/wiced_hal_nvram.h>

enum {
    PLATFORM_NVRAM_SSID_OPENTHREAD_BASE = WICED_NVRAM_SSID_START + 0x0000,
    PLATFORM_NVRAM_SSID_MATTER_BASE     = WICED_NVRAM_SSID_START + 0x0100,

    PLATFORM_NVRAM_ID_ENTRY_INFO_UINT16 = WICED_NVRAM_VSID_START + 0x0000,
    PLATFORM_NVRAM_ID_ENTRY_INFO_STRING = WICED_NVRAM_VSID_START + 0x0001,
    PLATFORM_NVRAM_ID_ENTRY_DATA_UINT16 = WICED_NVRAM_VSID_START + 0x0100,
    PLATFORM_NVRAM_ID_ENTRY_DATA_STRING = WICED_NVRAM_VSID_START + 0x0200,
    PLATFORM_NVRAM_VSID_MATTER_BASE     = WICED_NVRAM_VSID_START + 0x0400,
};
